version: '3'

services:
  backend:
    build:
      context: ./portfolio-be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"


  frontend:
    build:
      context: ./portfolio-fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./detailing-fe:/app